### ISSUE TITLE
devDemos are painfully slow

### ISSUE THREAD

**Issue by Sebring** [craftyjs/demos#3]
A lot of the platform-based demos in devDemos are painfully slow, including movement for the pong-paddles.

~~Maybe related to `Gravity-component`?~~ 

Seems the `speed`-values for the `Multiway` and `Twoway` are set extremely low. `Gravity`-value is also set low.

**Comment by starwed** [comment]
>Seems the speed-values for the Multiway and Twoway are set extremely low. Gravity-value is also set low.

Yup, in 7.0 point we switched speed units from pixels per frame to pixels per second, which means the demos are about 50 times too slow.  There's a conversion mentioned [here](https://github.com/craftyjs/Crafty/pull/923#issuecomment-120718636).

**Comment by Sebring** [comment]
Ok, I see - that is a welcome update.

Thanks for the link with conversation. I forked with the ambition to provide a PR within a few days, I hope it's welcome.

psst
> Yup, in 7.0 point we switched 

Let's get that 1.0.0 milestone first, then worry about 7.0!
(typo.. i know - 0.7 ;)

**Comment by mucaho** [comment]
resolved via #4.
